basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
	url(r'^register/$', views.register, name='register'),
	url(r'^login/$', views.user_login, name='user_login'),
	url(r'^logout/$', views.user_logout, name='logout'),
]

learning_users/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from basic_app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^', include('basic_app.urls'))
]

basic_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

class UserProfileInfo(models.Model):
	user = models.OneToOneField(User)
	portfolio_site = models.URLField()
	# upload to folder in media folder
	picture = models.ImageField(upload_to='images')

basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())

	class Meta():
		model = User
		fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
	picture = forms.ImageField(required=False)
	class Meta():
		model = UserProfileInfo
		fields = ('portfolio_site', 'picture')

basic_app/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileForm

from django.contrib.auth import login, logout, authenticate
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required



def index(request):
	return render(request, 'basic_app/index.html')

def register(request):
	registered = False

	if request.method == "POST":
		user_form = UserForm(data=request.POST)
		profile_form = UserProfileForm(data=request.POST)

		if user_form.is_valid() and profile_form.is_valid():
			print("user and form valid")
			user = user_form.save()
			user.set_password(user.password)
			user.save()

			print('user saved!')
			profile = profile_form.save(commit=False)
			profile.user = user

			print("request files: %s"%request.FILES)

			if 'picture' in request.FILES:
				print('picture found!')
				profile.picture = request.FILES['picture']

			profile.save()

			registered = True

		else:
			print(user_form.errors, profile_form.errors)

	else:
		user_form = UserForm()
		profile_form = UserProfileForm()

	print(registered)	

	return render(request, 'basic_app/registration.html', { 'user_form':user_form,
															'profile_form':profile_form,
															'registered':registered })


def user_login(request):

	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')

		user = authenticate(username=username, password=password)

		if user:
			if user.is_active:
				login(request, user)
				return HttpResponseRedirect(reverse('index'))
			else:
				return HttpResponse("USER IS NOT ACTIVE")
		else:
			return HttpResponse("login username {} and password {} are not permitted" .format(username, password))
	else:
		return render(request, 'basic_app/login.html', {})


@login_required
def user_logout(request):
	logout(request)
	return HttpResponseRedirect(reverse('index'))

templates/basic_app/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title></title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
  		<a class="navbar-brand" href="{% url 'index' %}">Django</a>
  		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    		<span class="navbar-toggler-icon"></span>
  		</button>
  		<div class="collapse navbar-collapse" id="navbarNav">
    		<ul class="navbar-nav">
      			<li class="nav-item active">
        			<a class="nav-link" href="{% url 'index' %}">Home</a>
      			</li>
      			<li class="nav-item">
        			<a class="nav-link" href="{% url 'basic_app:register' %}">Registration</a>
      			</li>
      			<li class="nav-item">
        			<a class="nav-link disabled" href="{% url 'admin:index' %}" tabindex="-1" aria-disabled="true">Admin</a>
      			</li>
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'basic_app:logout' %}">Logout</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'basic_app:user_login' %}">Login</a>
              </li>
            {% endif %}
            <li cla
    		</ul>
  		</div>
	</nav>

	<div class="container">
		{% block body_block %}
		{% endblock %}
	</div>
</body>
</html>

templates/basic_app/index.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
	{% block body_block %}
		<div class="jumbotron">
			<h1>Welcome to the home page!</h1>
		</div>
	{% endblock %}

templates/basic_app/login.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
	{% block body_block %}
		<div class="jumbotron">
			<h1>PLease Login</h1>
			<form action="{% url 'basic_app:user_login' %}" method="POST" >
				{% csrf_token %}
				<label for="username" >Username:</label>
				<input name="username" type="text" placeholder="Enter Username Here" />
				<label for="password" >Password:</label>
				<input name="password" type="password" />
				<input type="submit" class="btn btn-primary" value="Submit" />
			</form>

		</div>
	{% endblock %}

templates/basic_app/registration.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
	{% block body_block %}
		<div class="jumbotron">
			{% if registered %}
				<h1>Thank You For Registering!</h1>
			{% else %}
				<h1>Register Here!</h1>
				<h3>Please fill in the form</h3>
				<form enctype="multipart/form-data" method="POST">
					{% csrf_token %}
					{{ user_form.as_p }}
					{{ profile_form.as_p }}
					<input type="submit" value="Register">
				</form>
			{% endif %}
		</div>
	{% endblock %}